export const animations = {
  linAnimation: require('./../../assets/animations/LineAnimation.json'),
  burger: require('./../../assets/animations/HamburgerArrow.json'),
  logo: require('./../../assets/animations/LottieLogo1.json'),
  logo_2: require('./../../assets/animations/LottieLogo2.json'),
  walkThrough: require('./../../assets/animations/LottieWalkthrough.json'),
  watermelon: require('./../../assets/animations/Watermelon.json'),
  squares: require('./../../assets/animations/9squares-AlBoardman.json'),
  corpse: require('./../../assets/animations/MotionCorpse-Jrcanest.json'),
  pinJump: require('./../../assets/animations/PinJump.json'),
  twitterHeart: require('./../../assets/animations/TwitterHeart.json'),
  circleLoading: require('./../../assets/animations/circle-loading-animation.json'),
  circleLoading_2: require('./../../assets/animations/circle-animation.json'),
  offline: require('./../../assets/animations/offline.json'),
  car: require('./../../assets/animations/car.json'),
  emptyCart: require('./../../assets/animations/empty_cart.json'),
  cart: require('./../../assets/animations/cart.json'),
  expoLoading: require('./../../assets/animations/expo_loading.json'),
  emptyShape: require('./../../assets/animations/empty_shape.json'),
  animationCollection: [
    'bounceIn',
    'bounceInDown',
    'bounceInUp',
    'bounceInLeft',
    'bounceInRight',
  ],
  animationSingleElement: ['bounceInLeft', 'bounceInRight', 'pulse'],
  bounceIn: 'bounceIn',
  pulse: 'pulse',
  shake: 'shake',
  flip: 'flipInY',
};
