export const images = {
  pin: require('./../../assets/images/pin.png'),
  cartEmpty: require('./../../assets/images/cart_empty.png'),
  cartBg: require('./../../assets/images/cart_bg.png'),
  star: require('./../../assets/images/star.png'),
  loading: require('./../../assets/images/loading.gif'),
  loadingSm: require('./../../assets/images/loading_sm.gif'),
  whiteBg: require('./../../assets/images/whiteBg.png'),
  grayBg: require('./../../assets/images/grayBg.png'),
  knet: require('./../../assets/images/knet-visa.png'),
  whiteBgUrl: 'https://via.placeholder.com/100/fffffff/fffffff?text=text',
};

export const icons = {
  user: require('./../../assets/icons/user.png'),
  userTwo: require('./../../assets/icons/user_2.png'),
  userThree: require('./../../assets/icons/user_3.png'),
  info: require('./../../assets/icons/info.png'),
  home: require('./../../assets/icons/home.png'),
  homeTwo: require('./../../assets/icons/home_2.png'),
  homeThree: require('./../../assets/icons/home_3.png'),
  designerat: require('./../../assets/icons/designerat.png'),
  hanger: require('./../../assets/icons/hanger.png'),
  profile: require('./../../assets/icons/profile.png'),
  compass: require('./../../assets/icons/compass.png'),
  colorFilter: require('./../../assets/icons/color_filter.png'),
  categoryFilter: require('./../../assets/icons/category_filter.png'),
  categories: require('./../../assets/icons/categories.png'),
  categoriesSecond: require('./../../assets/icons/categories_2.png'),
  globe: require('./../../assets/icons/globe.png'),
  globeTwo: require('./../../assets/icons/globe_2.png'),
  cart: require('./../../assets/icons/cart.png'),
  cartThree: require('./../../assets/icons/cart_3.png'),
  cartFore: require('./../../assets/icons/cart_4.png'),
  cartFive: require('./../../assets/icons/cart_5.png'),
  cartSix: require('./../../assets/icons/cart_6.png'),
  policy: require('./../../assets/icons/policy.png'),
  contactus: require('./../../assets/icons/contactus.png'),
  phone: require('./../../assets/icons/phone.png'),
  female: require('./../../assets/icons/female.png'),
  gearOne: require('./../../assets/icons/gears.png'),
  gearTwo: require('./../../assets/icons/gear_2.png'),
  deliveryOne: require('./../../assets/icons/delivery_1.png'),
  deliveryTwo: require('./../../assets/icons/delivery_2.png'),
  bagOne: require('./../../assets/icons/bag_1.png'),
};
